### ISSUE TITLE
JBR genome browser doesn't respond

### ISSUE THREAD

**Issue by CarrollNew** [JetBrains-Research/jbr#64] opened 2019-04-25 11:31 UTC
I used it on Linux Ubuntu LTS 16.04 
![image](https://user-images.githubusercontent.com/43321024/56732551-75ab5a80-6766-11e9-9d97-92871be19c68.png)

I experience problems with UI.
![image](https://user-images.githubusercontent.com/43321024/56732611-9f648180-6766-11e9-99e9-0fd0787039fc.png)

Log file 
[jbr.log](https://github.com/JetBrains-Research/jbr/files/3116665/jbr.log)

**Comment by olegs** [comment] 2020-04-14 18:35
@CarrollNew Sorry for the late reply. We tried to reproduce the issue locally, but didn't managed to get same problems. At the moment we are going to release the next version of JBR based on Amazon Corrette JDK. Could you please try the release candidate version available by the link: 
https://artyomovlab.wustl.edu/publications/supp_materials/4Oleg/jbr-1.0.beta.5096.tar.gz

**Comment by olegs** [comment] 2020-04-28 09:23
Closing as cannot reproduce, will reopen once we face similar issues.

**Closed by olegs** 2020-04-28 09:23 UTC
