### ISSUE TITLE
JBR - cannot open SICER results without any extension

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/jbr#52] opened 2019-03-25 12:54 UTC
SICER without input yields result file without any extension.
Open BED files action should allow to pick any file.

**Comment by dievsky** [comment] 2019-03-25 15:47
Does it? I thought SICER no-control peaks were `.scoreisland`.

**Comment by olegs** [comment] 2019-03-25 15:53
Well I am not 100% sure, however one of my students had some issue with this. 
Probably allowing to use any file type will help in corner cases.

**Comment by iromeo** [comment] 2019-03-25 18:54
Is duplicate of https://github.com/JetBrains-Research/jbr/issues/53

P.S:
> Does it? I thought SICER no-control peaks were .scoreisland.

Correct, see https://github.com/JetBrains-Research/washu/issues/27#issuecomment-440221381

> Well I am not 100% sure, however one of my students had some issue with this.

The issue is for "with control" case.

**Closed by iromeo** 2019-03-25 18:54 UTC
Labels: bug, enhancement
